### ISSUE TITLE
[META] Bootstrap the LoongArch container-computing ecosystem

### ISSUE THREAD

**Issue by xen0n** [loongson-community/discussions#73]
> [!NOTE]
>
> 根据 https://github.com/docker-library/official-images/issues/16404#issuecomment-2173733639 ，有“合规要求” :eyes: 近期应该是不能给**官方**镜像加入 `linux/loong64` 支持了。不要指望用纯技术的方式解决此问题，但有政治雄心的贡献者倒是可以试试非技术的手段。 :eyes:
>
> 闲话不多说，目前我们主要聚焦于提供“影子”或曰“平行宇宙”的官方容器镜像，以放在另一个账号（例如[这个](https://hub.docker.com/r/loong64)，类似 [RISC-V 的相似用途账号](https://hub.docker.com/r/riscv64)）或者另一个容器镜像托管服务上的方式进行。
>
> According to https://github.com/docker-library/official-images/issues/16404#issuecomment-2173733639, there are "compliance requirements" :eyes: that likely precludes inclusion of `linux/loong64` variants in the *official* images in the short term. This is unlikely to get solved in a purely technical manner, but anyone with the political ambitions can always try. :eyes:
>
> In the meantime though, we focus our work on providing "shadow"/"parallel-universe" "official" container images under a different account (e.g. [this](https://hub.docker.com/r/loong64), akin to [the RISC-V one](https://hub.docker.com/r/riscv64)) / container registry.

* [ ] Infra
    * [ ] https://github.com/estesp/manifest-tool/pull/274
    * [ ] https://github.com/docker-library/bashbrew/pull/108
* [ ] Alpine
    * [ ] official (`alpine`): **blocked due to non-technical reasons**, https://github.com/docker-library/official-images/pull/17607
    * [ ] unofficial: TBD
* [ ] Debian
    * [ ] official (`debian`): **likely also blocked**, https://github.com/debuerreotype/docker-debian-artifacts/issues/220
    * [ ] unofficial: TBD
* more to come

**Comment by fossdd** [comment]
btw: alpine does try to find another location to distribute the container images, so stay tuned.

**Comment by darkyzhou** [comment]
I have strong demand for a stable Debian image for my project. I understand the compliance issues with official images, and I'm willing to help build the unofficial version.

**Comment by xen0n** [comment]
Some more information so far:

* The [`loong64` organization](https://github.com/loong64) is supposedly transferred to Loongson by its original owner. Some container images are being produced with automation right now, but the build system there may need some more scrutiny before one (actually, personally I) could trust.
* The [`loong64` Docker Hub account](https://hub.docker.com/u/loong64) was registered by an unknown individual (maybe an Loongson employee but they haven't been able to pinpoint so far) and thus not usable.
* So far Loongson's cloud computing group has been uploading manually crafted images under [the Docker Hub account `loongarch64`](https://hub.docker.com/u/loongarch64). The account name may be misleading because in the cloud ecosystem people are used to `GOARCH`-like architecture names where `loongarch64` is the old-world name for LoongArch64.

I've contacted the Loongson team and pointed them here, but so far they haven't (or couldn't) comment.

**Comment by fossdd** [comment]
Alpine now officially has loongarch64 images ready at `registry.alpinelinux.org/img/alpine`: https://gitlab.alpinelinux.org/img/alpine/
